baseURL = "https://psanat.github.io/first-hugo-site/"
languageCode = "en-us"
title = "XYZ"
canonifyURLs = true
relativeURLs = false

paginate = 2

[taxonomies]
tag = "tags"

[params]
description = "A simple Hugo Website"

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4

[[menu.footer]]
name = "FAQs"
url = "/common-faqs/"
weight = 1

[[menu.footer]]
name = "Terms & Conditions"
url = "/legal/terms-and-conditions/"
weight = 2

[[menu.footer]]
name = "Privacy Policy"
url = "/legal/privacy-policy/"
weight = 3